using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EzIna.Motion
{
    //MotionAeroDefinition

    public class stTaskInfor
    {
        public string strProgram;
        public string strState;
        public string strErr;
        public Aerotech.A3200.Tasks.TaskState eState;
        public stTaskInfor()
        {
            Clear();
        }
        public void Clear()
        {
            strProgram = "";
            strState = "";
            strErr = "";

            eState = Aerotech.A3200.Tasks.TaskState.Idle;
        }
    }

    public class MotionAero_DEF
    {

        #region enum
        public enum eAeroI_1
        {
            //output 4, 
            //Input  6
            X08 = 8,
            X09,
            X10,
            X11,
            X12,
            X13
        }
        public enum eAeroO_1
        {
            Y08 = 8,
            Y09,
            Y10,
            Y11

        }
        public enum eAeroIO_SW
        {
            Off = 0,
            On
        }
        public enum A3200_DATASIGNAL
        {
            CurrentFeedback = 7,
            CurrentCommand = 8,
            AnalogInput0 = 10,
            AnalogInput1 = 11,
            PhaseACurrentFeedback = 24,
            PhaseBCurrentFeedback = 25,
            EncoderSine = 26,
            EncoderCosine = 27,
            AnalogInput2 = 28,
            AnalogInput3 = 29,
            LoopTransmissionBefore = 30,
            LoopTransmissionAfter = 31,
            ZHSDifference = 32,
            ZHSSum = 33,
            ZHSUnfiltered = 34,
            ZHSFiltered = 35,
            AnalogOutput0 = 36,
            AnalogOutput1 = 37,
            AnalogOutput2 = 38,
            AnalogOutput3 = 39,
            DriveMemoryInt32 = 40,
            DriveMemoryFloat = 41,
            DriveMemoryDouble = 42,
            PSOStatus = 43,
            DriveTimer = 44,
            PositionFeedbackDrive = 88,
            PositionCommandDrive = 98,
            DriveMemoryInt16 = 157,
            DriveMemoryInt8 = 158,
            DriveMemoryInt32Pointer = 202,
            DriveMemoryInt16Pointer = 203,
            DriveMemoryInt8Pointer = 204,
            DriveMemoryFloatPointer = 205,
            DriveMemoryDoublePointer = 206,
            PSOCounter1 = 229,
            PSOCounter2 = 230,
            PSOCounter3 = 231,
            PSOWindow1 = 232,
            PSOWindow2 = 233,
            DataAcquisitionSamples = 234,
            PositionDetectorVoltage = 235,
            PositionCommandGalvo = 237,
            ResolverChannel1 = 267,
            ResolverChannel2 = 268,
            EnDatAbsolutePosition = 269,
            ControlEffort = 282,
            ModbusBitMasterInputBits = 290,
            ModbusBitMasterOutputBits = 291,
            ModbusRegInt16MasterInputWords = 292,
            ModbusRegInt16MasterOutputWords = 293,
            ModbusRegInt32MasterInputWords = 294,
            ModbusRegInt32MasterOutputWords = 295,
            ModbusRegSingleMasterInputWords = 296,
            ModbusRegSingleMasterOutputWords = 297,
            ModbusRegDoubleMasterInputWords = 298,
            ModbusRegDoubleMasterOutputWords = 299,
            PhaseAVoltageCommand = 300,
            PhaseBVoltageCommand = 301,
            PhaseCVoltageCommand = 302,
            AmplifierPeakCurrent = 303,
            FPGAVersion = 304,
            DriveTypeID = 305,
            PSOWindow1ArrayIndex = 306,
            PSOWindow2ArrayIndex = 307,
            PSODistanceArrayIndex = 308,
            AmplifierTemperature = 309,
            PSOBitArrayIndex = 310,
            MXAbsolutePosition = 311,
            ServoUpdateRate = 312,
            SettlingTime = 313,
            InternalErrorCode = 314,
            FirmwareVersionMajor = 315,
            FirmwareVersionMinor = 316,
            FirmwareVersionPatch = 317,
            FirmwareVersionBuild = 318,
            DriveTimerMax = 319,
            MarkerSearchDistance = 320,
            PositionFeedbackGalvo = 327,
            LatchedMarkerPosition = 331,
            TemperatureSensor = 332,
            EthernetDebuggingInformation = 365,
            NpaqSyncoutStatus = 366,
            ResoluteAbsolutePosition = 369,
            FaultPositionFeedback = 372,
            MotorCommutationAngle = 373,
            IOBoardInstalled = 374,
            BusVoltage = 375,
            PiezoVoltageCommand = 376,
            PiezoVoltageFeedback = 377,
            TimeSinceReset = 387,
            MaximumVoltage = 388,
            CommandOutputType = 389,
            DriveFeedforwardOutput = 404,
            LastTickCounter = 405,
            BoardRevision = 407,
            FirmwareRevision = 408,
            GalvoLaserOutput = 409,
            GalvoLaserPowerCorrectionOutput = 414,
            CapacitanceSensorRawPosition = 415,
            PositionCalibrationGalvo = 419,
            BusVoltageNegative = 441,
            ProcessorTemperature = 442,
            InternalErrorTimestamp = 444,
            AmplifierInformation = 445,
            AnalogSensorInput = 446,
            MotorTemperature = 447,
            ResoluteStatus = 449,
            PSOExternalSyncFrequency = 454,
            PositionFeedback = 0,
            PositionCommand = 1,
            PositionError = 2,
            VelocityFeedback = 3,
            VelocityCommand = 4,
            VelocityError = 5,
            AccelerationCommand = 6,
            CurrentError = 9,
            PositionCommandRaw = 12,
            VelocityCommandRaw = 13,
            PositionFeedbackAuxiliary = 14,
            DigitalInput = 15,
            DigitalOutput = 16,
            FixtureOffset = 18,
            CoordinatedPositionTarget = 46,
            DriveStatus = 47,
            AxisStatus = 48,
            AxisFault = 49,
            AccelerationCommandRaw = 50,
            PositionCalibrationAll = 55,
            PositionFeedbackRollover = 69,
            PositionCommandRollover = 70,
            PositionFeedbackAuxiliaryRollover = 71,
            VelocityFeedbackAverage = 72,
            CurrentFeedbackAverage = 73,
            AxisParameter = 76,
            PeakCurrent = 78,
            Backlash = 81,
            HomeState = 82,
            PositionCalibration2D = 83,
            NormalcyDebug = 84,
            TotalMoveTime = 85,
            Stability0SettleTime = 86,
            Stability1SettleTime = 87,
            JerkCommandRaw = 89,
            ProgramPositionCommand = 90,
            GantryOffset = 91,
            PositionOffset = 92,
            CommunicationRealTimeErrors = 93,
            PositionCommandRawBackwardsDiff = 96,
            VelocityCommandRawBackwardsDiffDelta = 97,
            DriveStatusActual = 99,
            GantryRealignState = 100,
            TransformAutoOffset = 101,
            ProgramPositionFeedback = 107,
            JogTrajectoryStatus = 116,
            PingTest = 117,
            GainKposScale = 126,
            GainKiScale = 127,
            GainKpScale = 128,
            GainKpiScale = 129,
            GainAffScale = 130,
            GainVffScale = 131,
            AccelerationTime = 138,
            DecelerationTime = 139,
            AccelerationRate = 140,
            DecelerationRate = 141,
            AccelerationType = 142,
            DecelerationType = 143,
            AccelerationMode = 144,
            DecelerationMode = 145,
            ProgramPosition = 156,
            SpeedTarget = 160,
            PositionCommandPacket = 163,
            DriveSMCMotionState = 168,
            PositionCommandRawCal = 178,
            VelocityCommandRawCal = 179,
            VelocityCommandDrive = 180,
            AccelerationCommandDrive = 181,
            GalvoLaserOutputRaw = 183,
            DriveInterfacePacketInt32 = 186,
            DriveInterfacePacketInt16 = 187,
            DriveInterfacePacketInt8 = 188,
            DriveInterfacePacketDouble = 189,
            DriveInterfacePacketFloat = 190,
            DriveInterfaceCommandCode = 191,
            AccelerationFeedback = 192,
            AccelerationCommandRawCal = 193,
            PositionCalibrationAllDrive = 194,
            BacklashTarget = 196,
            DriveMotionRate = 198,
            DriveMotionDelay = 199,
            CalibrationAdjustmentValue = 200,
            ServoRounding = 201,
            FeedforwardCurrent = 208,
            DriveInterfacePacketInfoBitValue = 210,
            AccelerationError = 223,
            SuppressedFaults = 225,
            DriveInterfacePacketStreamingData = 226,
            PositionCommandRawUnfiltered = 227,
            TransitionOffsetErrors = 228,
            FreezeVelocityCommand = 238,
            FreezeVelocityFeedback = 239,
            InternalPositionOffsets = 241,
            StatusHighLevelOffsetsLastMsec = 242,
            ProgramVelocityCommand = 250,
            ProgramVelocityFeedback = 251,
            DriveMotionDelayLive = 252,
            DriveCommunicationDelay = 253,
            DriveCommunicationDelayLive = 254,
            DriveInterfacePacketResponseInt32 = 256,
            DriveInterfacePacketResponseInt16 = 257,
            DriveInterfacePacketResponseInt8 = 258,
            DriveInterfacePacketResponseDouble = 259,
            DriveInterfacePacketResponseFloat = 260,
            DriveInterfacePacketBit = 261,
            DriveInterfacePacketResponseBit = 262,
            SpeedTargetActual = 266,
            CoordinatedDistanceRemaining = 272,
            SafeZoneState = 323,
            PositionErrorGalvo = 328,
            GainKd1Scale = 333,
            GainKp1Scale = 334,
            MoveReferencePosition = 339,
            MoveReferenceCutterOffset = 358,
            MoveReferenceCornerOffset = 359,
            MoveReferenceTotalOffset = 360,
            GantryMarkerLatchPosition = 368,
            DistanceLog = 378,
            AutoFocusError = 410,
            GalvoLaserOutputRawAdvance = 411,
            GalvoLaserOnDelay = 412,
            GalvoLaserOffDelay = 413,
            CalibrationAdjustmentState = 416,
            AccuracyCorrectionStartingPosition = 417,
            AccuracyCorrectionEndingPosition = 418,
            DriveCommandsDelayed = 424,
            DriveCommandsLost = 425,
            STOStatus = 443,
            DriveAssert = 453,
            VirtualBinaryInput = 51,
            VirtualBinaryOutput = 52,
            VirtualRegisterInput = 53,
            VirtualRegisterOutput = 54,
            Timer = 56,
            TimerPerformance = 57,
            GlobalVariable = 74,
            LibraryCommand = 148,
            DataCollectionSampleTime = 149,
            DataCollectionSampleIndex = 161,
            ZYGOPosition1 = 164,
            ZYGOPosition2 = 165,
            ZYGOPosition3 = 166,
            ZYGOPosition4 = 167,
            PCModbusMasterConnected = 170,
            PCModbusSlaveConnected = 171,
            PCModbusMasterErrorCode = 174,
            PCModbusSlaveErrorCode = 175,
            PCModbusMasterErrorLocation = 176,
            PCModbusSlaveErrorLocation = 177,
            StopWatchTimer = 197,
            ScopetrigID = 209,
            EstimatedProcessorUsage = 236,
            DataCollectionStatus = 255,
            SignalLogState = 270,
            FieldbusConnected = 284,
            FieldbusErrorCode = 285,
            FieldbusErrorLocation = 286,
            FieldbusActiveConnections = 287,
            FieldbusInactiveConnections = 288,
            SafeZoneViolationMask = 289,
            SafeZoneActiveMask = 321,
            FieldbusInputs = 340,
            FieldbusOutputs = 341,
            ModbusMasterInputWords = 342,
            ModbusMasterOutputWords = 343,
            ModbusMasterInputBits = 344,
            ModbusMasterOutputBits = 345,
            ModbusMasterOutputStatusBits = 346,
            ModbusMasterOutputStatusWords = 347,
            ModbusSlaveInputWords = 348,
            ModbusSlaveOutputWords = 349,
            ModbusSlaveInputBits = 350,
            ModbusSlaveOutputBits = 351,
            DriveModbusMasterInputWords = 352,
            DriveModbusMasterOutputWords = 353,
            DriveModbusMasterInputBits = 354,
            DriveModbusMasterOutputBits = 355,
            DriveModbusMasterOutputStatusBits = 356,
            DriveModbusMasterOutputStatusWords = 357,
            SystemParameter = 379,
            ThermoCompSensorTemperature = 420,
            ThermoCompControllingTemperature = 421,
            ThermoCompCompensatingTemperature = 422,
            ThermoCompStatus = 423,
            StepperVerificationMask = 426,
            ProgramLineNumber = 17,
            CoordinatedFlags = 45,
            CoordinatedArcStartAngle = 58,
            CoordinatedArcEndAngle = 59,
            CoordinatedArcRadius = 60,
            CoordinatedArcRadiusError = 61,
            CoordinatedPositionCommand = 62,
            CoordinatedSpeedCommand = 63,
            CoordinatedAccelerationCommand = 64,
            CoordinatedTotalDistance = 65,
            CoordinatedPercentDone = 66,
            CoordinatedPositionCommandBackwardsDiff = 67,
            ProgramVariable = 75,
            TaskParameter = 77,
            TaskErrorCode = 79,
            TaskWarningCode = 80,
            WaitCommandDuration = 103,
            CoordinatedSpeedTargetActual = 104,
            DependentCoordinatedSpeedTargetActual = 105,
            ActiveFixtureOffset = 106,
            TaskStatus0 = 108,
            TaskStatus1 = 109,
            TaskStatus2 = 110,
            Spindle0SpeedTarget = 112,
            Spindle1SpeedTarget = 113,
            Spindle2SpeedTarget = 114,
            Spindle3SpeedTarget = 115,
            CoordinateSystem1I = 118,
            CoordinateSystem1J = 119,
            CoordinateSystem1K = 120,
            CoordinateSystem1Plane = 121,
            ToolNumberActive = 122,
            MFO = 123,
            CoordinatedSpeedTarget = 124,
            DependentCoordinatedSpeedTarget = 125,
            CoordinatedAccelerationRate = 132,
            CoordinatedDecelerationRate = 133,
            CoordinatedAccelerationTime = 134,
            CoordinatedDecelerationTime = 135,
            TaskMode = 137,
            TaskState = 146,
            TaskStateInternal = 147,
            ExecutionMode = 151,
            TaskErrorLocation = 152,
            TaskWarningLocation = 153,
            ProgramPersistent = 154,
            ImmediateState = 155,
            EnableAlignmentAxes = 159,
            QueueStatus = 162,
            CoordinatedGalvoLaserOutput = 169,
            CoordinatedMotionRate = 184,
            CoordinatedTaskCommand = 185,
            FiberMoveCount = 195,
            EnableState = 224,
            CannedFunctionID = 240,
            TaskDoubleVariable = 248,
            TaskInfoVariable = 249,
            TaskReturnVariable = 271,
            FiberPower = 273,
            FiberPowerOptimal = 274,
            FiberPowerSampleCount = 275,
            FiberSearchResult = 276,
            LookaheadMovesExamined = 278,
            ProgramLineNumberInternal = 322,
            ProfileControlMask = 324,
            QueueLineCount = 325,
            QueueLineCapacity = 326,
            ImmediateCommandErrorCode = 329,
            ImmediateCommandErrorLocation = 330,
            CoordinatedArcRadiusReciprocal = 363,
            MotionEngineStage = 367,
            CoordinatedTimeScale = 370,
            CoordinatedTimeScaleDerivative = 371,
            IFOVSpeedScale = 380,
            IFOVSpeedScaleAverage = 381,
            IFOVGenerationFrameCounter = 382,
            IFOVGenerationTimeOriginal = 383,
            IFOVGenerationTimeModified = 384,
            IFOVCoordinatedPositionCommand = 385,
            IFOVCoordinatedSpeedCommand = 386,
            IFOVCenterPointH = 390,
            IFOVCenterPointV = 391,
            IFOVTrajectoryCount = 392,
            IFOVTrajectoryIndex = 393,
            IFOVAttemptCode = 394,
            IFOVGenerationFrameIndex = 395,
            IFOVMaximumVelocity = 396,
            IFOVIdealVelocity = 397,
            TaskInternalDebug = 398,
            IFOVCoordinatedAccelerationCommand = 399,
            IFOVFOVPositionH = 400,
            IFOVFOVPositionV = 401,
            IFOVFOVDimensionH = 402,
            IFOVFOVDimensionV = 403,
            MotionBufferElements = 427,
            MotionBufferMoves = 428,
            MotionLineNumber = 429,
            MotionBufferRetraceMoves = 430,
            MotionBufferRetraceElements = 431,
            MotionBufferIndex = 432,
            MotionBufferIndexLookahead = 433,
            MotionBufferProcessingBlocked = 434,
            ActiveMoveValid = 435,
            TaskExecutionLines = 436,
            SchedulerTaskHolds = 437,
            SchedulerProgramLoopRuns = 438,
            SchedulerTaskBlocked = 439,
            CriticalSectionActive = 440,
            AxesSlowdownReason = 448,
            TaskExecutionTime = 450,
            TaskExecutionTimeMaximum = 451,
            TaskExecutionLinesMaximum = 452,
            LookaheadDecelReason = 455,
            LookaheadDecelMoves = 456,
            LookaheadDecelDistance = 457,
        }
        #endregion enum

    }
    public class AeroTaskInfor
    {
        Aerotech.A3200.Tasks.Task m_pTask = null;
        stTaskInfor m_pTaskInfor = null;

        public stTaskInfor TaskInfor
        {
            get { return m_pTaskInfor; }
            set
            {
                if (m_pTaskInfor != null)
                {
                    m_pTaskInfor = value;
                }
            }
        }
        public Aerotech.A3200.Tasks.Task pTask
        {
            get { return m_pTask; }
        }

        public AeroTaskInfor(Aerotech.A3200.Tasks.Task a_pTask, stTaskInfor a_pTaskInfor)
        {
            m_pTask = a_pTask;
            m_pTaskInfor = a_pTaskInfor;
        }
    }
}
