[Error List]
1 = "Please proceed with initializing this equipment first"
2 = "This equipment initializing failed"
3 = "EMO Pushed"
4 = "Main Air Pressure Error"
7 = "Door Open before Run"
9 = "Servo Motor Power Off(XYZ)"
10= "Step Motor Power Off (Rail , Pinch roller)"
11="Lot Code Input Empty"
20="Motor Servo Off"
;RunningLoad Init
1440="Loading RAIL Mouth or POS Sensor Detected , Check in Side and remove JIG or ETC"
1443="Stopper Left or Center not work Down Action , Check Cylinder"
;RunningLoad Error
8010="JIG or Etc detected sensor , Check and Remove before Loading"  
8011="JIG or Etc detected sensor , Check and Remove before Loading"  
8020="Cylinder action timeout ,Check cylinder action" 
8021="Cylinder action timeout ,Check cylinder action" 
8030="Loader interface error"
8031="Loader interface Error"
8040="JIG isn't Detected after JIG Loading"
8041="JIG isn't Detected after JIG Loading "
8042="Unloading SEQ check timeout"
8043="JIG detect timeout until loading Pos Sensor"
8044="Loading X Axis Move done timeout"
8050="JIG Clamp action time out"
8051="JIG Clamp action time out"
8052="Center Stopper Cylinder down action timeout"
;RunningScanner Init
1140="JIG or Object detected , remove object before Initialize"
1141="JIG or Object detected , remove object before Initialize"
1143="Cylinder down action timeout (stopper_L ,stopper_center)"
;RunningScanner SEQ
10010="Recipe verification fail" 
10011="Recipe verification fail" 
10020="JIG Not Exist or JIG isn't Clamp"
10021="JIG Not Exist or JIG isn't Clamp"
10030="IO Check Fail"
10031="IO Check Fail"
10040="Center Stopper down action Fail"
10041="Center Stopper down action timeout"
10050="Position move command timeout"
10051="Position move inposition timeout"
10060="none"
10061="none"
10062="Camera idle status change timeout"
10063="JIG Code Insp Light Setting Timeout"
10064="JIG Code Insp Light Setting Timeout"
10065="Camera Idle status change timeout before grab"
10066="Camera grab timeout (fail)"
10067="Jig Code isn't detected(scan fail)"
10068="Jig Code isn't detected(scan fail)"
10070="MES Connect timeout (fail)"
10071="MES MarkingStart Fail"
10080="none"
10081="Stage isn't ready status ( not inposition or motiondone )"
10082="Position move command timeout"
10083="Position move done timeout"
10090="none"
10091="none"
10092="Camera idle status change timeout before grab
10093="Match Light value set timeout"
10094="Match Light value set check timeout"
10095="Vision(match) Insp config setting fail"
10096="Vision(match) Insp config setting fail"
10100="Camera grab command timeout(fail)"
10101="Camera grab timeout(fail)"
10102="none"
10103="none"
10104="none"
10110="Marking parameter setting fail"
10111="Marking Laser Mode set & check fail"
10112="Marking Laser Mode set & check fail"
10113="Marking Laser Mode set & check fail"
10114="Laser Emission Enable active timeout"
10115="Marking Param Check Error (Laser Power)"
10116="none"
10117="none"
10118="none"
10120="Scanner Calibration File load fail"
10121="DataMatrix Path Create Fail"
10122="DataMatrix Path Create Fail"
10123="none"
10130="none"
10131="none"
10132="none"
10133="Light Set Value timeout before marking INSP"
10134="Light Set Value check timeout before marking INSP"
10135="Image Grab time out before marking INSP"
10136="Image Grab time out before marking INSP"
10137="Marking INSP Run timeout"
10138="none"
10140="none"
10141="none"
10150="MES connect timeout"
10151="MES marking Report error"
10160="none"
10161="MES connect timeout"
10162="MES marking end error"
10163="Exist Marking error product"
10164="none"
;RunningScanner Init SEQ
1140="XYZ Driver Power Off"
1150="JIG FEEDER L,R unclamp action timeout"
1151="JIG FEEDER L,R unclamp action done check timeout"
1160="XYZ Servo On timeout"
1161="XYZ HomeStart command timeout"
1162="XYZ Home done check timeout"
;RunningUnload SEQ
8010="IO Check Fail before unloading"
8011="none"
8020="none"
8021="none"
8040="none"
8041="Stopper L,R Down action timeout"
8042="Stopper L,R Down action done timeout"
8050="Unloading Pos X moving command timeout"
8051="Unloading Pos X moving done timeout"
8060="JIG Feeder Unclamp action timeout"
8061="JIG Feeder Unclamp action done check timeout"
8070="Unloading Pitch Roller move command timeout"
8071="JIG Unloading POS(to sensor) move or pinch roller stop command timeout"
8080="Unloader ready reply timeout"
8081="none"
8090="Unload mouth sensor JIG not detected"
8091="Unload pinch roller move command timeout"
8092="JIG Unload action timeout"
8093="Unload pinch roller stop check timeout"
;RunningUnload Init SEQ
1540="IO Check Error"
1541="none"
1542="Stopper R Down action timeout"
1543="Stopper R Down action done check timeout"

